### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by HJunyuan**
**Overview**
- Update dependencies
- Add sample `getDidSigner` keys to be used in test environment
- Add `.prettierrc` file
- Revert `lockfileVersion` from 2 to 1 since GitHub CI is still on node@12 and npm@6

**Code changes**
- `src/functionHandlers/notarisePdt/handler.ts`:
  - uuid import statement ([upgrade docs](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29))
  - middy v2.x now uses async handler ([upgrade docs](https://github.com/middyjs/middy/blob/main/docs/UPGRADE.md))
- `.eslintrc`:
  - Remove `"prettier/@typescript-eslint"` as Prettier configs are now merged into one ([upgrade docs](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21))

**On hold**
- `@govtechsg/oa-verify` to be upgraded in a separate PR due to the code changes required

### CODE REVIEW

**Comment by HJunyuan** [comment]
Ignore last commit (https://github.com/Notarise-gov-sg/api-notarise-healthcerts/pull/50/commits/4833595a3a6d163473a8d9e49d02e51057dcc62d) as it is just lint fixes

**Comment by eugbyte** [comment]
I am getting `Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.` when i run `npm run dev`

**Comment by eugbyte** [comment]
> 
> 
> I am getting `Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.` when i run `npm run dev`

https://www.npmjs.com/package/fork-ts-checker-webpack-plugin

If you edit the webpack to 
```
eslint: {
        files: './src/**/*.{ts,tsx,js,jsx}' 
      }
```
it works

**Comment by HJunyuan** [comment]
@eugbyte Thanks for highlighting, let me know if the latest commit works for you.

**Comment by eugbyte** [comment]
> 
> 
> @eugbyte Thanks for highlighting, let me know if the latest commit works for you.

Yup it works

**Review by eugbyte — APPROVED** [review]

**Pull request merged**
